name: Deploy

on:
  push:
    branches: [main]

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build & Deploy
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PK }}
          HOSTNAME: ${{secrets.SSH_HOST}}
          USER_NAME: ${{secrets.SSH_USER}} 

        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
 
            # Now we have got the access of EC2 and we will start the deploy .
              cd /home/ec2-user/repos/theraswift_backend_two 
              git checkout main 
              git pull origin main --force && echo UPDATED CODEBASE 
              node -v
              npm ci && echo INSTALLED DEPENDENCIES 
              npm run build && echo BUILT CODE 
              sudo rm -r /var/www/api &&  echo  REMOVED DIST DIRECTORY 
              sudo mkdir -p /var/www/api/dist &&  echo  MADE DIST DIRECTORY 
              sudo mv dist /var/www/api &&  echo  MOVED BUILT CODE 
              sudo mv node_modules /var/www/api/dist &&  echo MOVED DEPENDENCIES 
              cd /var/www/api/dist 
              npm start 
              exit
              '
